using System;
using System.Collections.Generic;

namespace RAMMS.Domain.Models
{
    public partial class AssetImport
    {
        public string AiAssetId { get; set; }
        public string AiDivCode { get; set; }
        public string AiDist { get; set; }
        public string AiRmuCode { get; set; }
        public string AiSecCode { get; set; }
        public string AiSecName { get; set; }
        public string AiRdCode { get; set; }
        public string AiRdName { get; set; }
        public string AiAssetGrpCode { get; set; }
        public string AiGrpType { get; set; }
        public string AiLocChKm { get; set; }
        public string AiLocChM { get; set; }
        public string AiBound { get; set; }
        public string AiStrucCode { get; set; }
        public string AiRefNo { get; set; }
        public string AiFeatureId { get; set; }
        public string AiDiameter { get; set; }
        public string AiWidth { get; set; }
        public string AiHeight { get; set; }
        public string AiMaterial { get; set; }
        public string AiFinRdLevel { get; set; }
        public string AiCatchArea { get; set; }
        public string AiSkew { get; set; }
        public string AiDesignFlow { get; set; }
        public string AiLength { get; set; }
        public string AiPrecastSitu { get; set; }
        public string AiBarrelNo { get; set; }
        public string AiIntelLevel { get; set; }
        public string AiIntelStruc { get; set; }
        public string AiOutletLevel { get; set; }
        public string AiOutletStruc { get; set; }
        public string AiOwner { get; set; }
        public string AiMaintainedBy { get; set; }
        public string AiGpsEasting { get; set; }
        public string AiGpsNorthing { get; set; }
        public string AiRiverName { get; set; }
        public string AiWidthLane { get; set; }
        public string AiLengthSpan { get; set; }
        public string AiBridgeName { get; set; }
        public string AiLaneCnt { get; set; }
        public string AiSpanCnt { get; set; }
        public string AiMedian { get; set; }
        public string AiWalkway { get; set; }
        public string AiStrucSuper { get; set; }
        public string AiParapetType { get; set; }
        public string AiBearingType { get; set; }
        public string AiExpanType { get; set; }
        public string AiDeckType { get; set; }
        public string AiAbutType { get; set; }
        public string AiPierType { get; set; }
        public string AiExpanJointCount { get; set; }
        public string AiExpanJointSpace { get; set; }
        public string AiAbutFound { get; set; }
        public string AiPiersPrimComp { get; set; }
        public string AiBearingSeatDiaphg { get; set; }
        public string AiBeamsGridTrusArch { get; set; }
        public string AiDeckPavement { get; set; }
        public string AiUtilities { get; set; }
        public string AiWaterway { get; set; }
        public string AiWaterDownpipe { get; set; }
        public string AiParapetRailing { get; set; }
        public string AiSidewalksAppSlab { get; set; }
        public string AiExpanJoint { get; set; }
        public string AiSlopeRetainWall { get; set; }
        public string AiBuiltYear { get; set; }
        public string AiFrmCh { get; set; }
        public string AiFrmChDeci { get; set; }
        public string AiToCh { get; set; }
        public string AiToChDeci { get; set; }
        public string AiLaneNo { get; set; }
        public string AiPostSpacing { get; set; }
        public string AiTier { get; set; }
        public string AiBotWidth { get; set; }
        public string AioAssetId { get; set; }
        public string AioAssetGrpCode { get; set; }
        public string AioStrucCodeOthers { get; set; }
        public string AioMaterialOthers { get; set; }
        public string AioAbutFoundOthers { get; set; }
        public string AioPiersPrimCompOthers { get; set; }
        public string AioBearingSeatDiaphgOthers { get; set; }
        public string AioBeamsGridTrusArchOthers { get; set; }
        public string AioDeckPavementOthers { get; set; }
        public string AioUtilitiesOthers { get; set; }
        public string AioWaterwayOthers { get; set; }
        public string AioWaterDownpipeOthers { get; set; }
        public string AioParapetRaiolingOthers { get; set; }
        public string AioSidewalksAppSlabOthers { get; set; }
        public string AioExpanJointOthers { get; set; }
        public string AioSlopeRetAionWallOthers { get; set; }
        public string RmAllassetInvOthers { get; set; }
        public string AiHasImage { get; set; }
        public string AssetImgPath { get; set; }
        public Guid? AiFileNo { get; set; }
        public string AiAssetNumber { get; set; }
        public string AiRmuName { get; set; }
        public string AiS8 { get; set; }
        public string AiImportErrorDesc { get; set; }
        public string AiAssetIdActual { get; set; }
        public int? AiRdmPkRefNo { get; set; }
        public int? AiSrno { get; set; }
        public string AiCulvertType { get; set; }
        public string AioGrpTypeOthers { get; set; }
        public string AioCulvertTypeOthers { get; set; }
    }
}
